### ISSUE TITLE
Multiple errors: Usage, AwaitMessage...

### ISSUE THREAD

**Issue by kyranet** [UnseenFaith/komada#169] opened 2017-03-26 11:15 UTC
### Version of Komada 
0.18.10, but it's present since years ago.

### Are core files modified? 
No

#### 1.- Usage
When a command uses the `mention` type in usage, and the user doesn't mention the user, it prints this message:
```js
[2017-03-26 12:24:45] TypeError: Cannot read property '0' of null
    at validateArgs (/mnt/c/Users/manue/node_modules/komada/functions/usage.js:103:82)
    at Promise (/mnt/c/Users/manue/node_modules/komada/functions/usage.js:580:4)
    at Object.exports.run (/mnt/c/Users/manue/node_modules/komada/functions/usage.js:9:55)
    at Object.module.exports [as handleCommand] (/mnt/c/Users/manue/functions/handleCommand.js:11:45)
    at client.on (/mnt/c/Users/manue/node_modules/komada/app.js:79:18)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

#### 2.- Boolean validator
Another thing in **usage.js** (L116-L121), it's validating if the argument is false, but not when it's true.
```js
if (args[i] === "true") {
  args[i] = true;
} else {
  args[i] = false;
  validateArgs(++i);
}
```

#### 3.- Awaitmessage
Also, now that we are here, add `if (message.deletable)` in L25 from awaitMessage, if you delete the message before it gets deleted, or komada couldn't send the message, it'll print this:
```js
Uncaught Promise Error:
TypeError: message.delete is not a function
    at module.exports (/mnt/c/Users/manue/node_modules/komada/functions/awaitMessage.js:25:19)
```

#### 4.- Commands
Also, I know that it's hard to catch, but if the bot has permissions to read a channel, but not to send a message into it, for example, the command ping:
```js
[2017-03-26 12:17:55] Error: Forbidden
    at Request.callback (/mnt/c/Users/manue/node_modules/superagent/lib/node/index.js:675:11)
    at /mnt/c/Users/manue/node_modules/superagent/lib/node/index.js:883:18
    at Stream.<anonymous> (/mnt/c/Users/manue/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:186:7)
    at Unzip.<anonymous> (/mnt/c/Users/manue/node_modules/superagent/lib/node/unzip.js:53:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Uncaught Promise Error:
TypeError: Cannot read property 'edit' of undefined
    at exports.run (/mnt/c/Users/manue/commands/System/ping.js:3:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Should check if the message is editable before "trying" to edit it.

#### 1.- Usage
Should run this line (L111) in case of `mention` type. I have checked the code and might be reproduceable for `member`. Since in `/\d+/.exec(args[i])[0]`, when there's no number, you're trying to read the property `[0]` of null.
```
return reject(client.funcs.newError(`${currentUsage.possibles[0].name} must be a mention or valid user id.`, 1, args));
```

#### 2.- Boolean validator
It should validate if the argument is either `true` or `false`, currently it does only for `false`.

#### 3.- Awaitmessage
Should verify if the message was sent and is editable, instead of trying to edit it.

#### 4.- Commands
Previously check if the command requires `SEND_MESSAGES` permissions before trying to run it. In `conf.botPerms`, maybe?

### Actual Behaviour
Everything explained above.

### Steps to Reproduce.
¯\\\_(ツ)\_/¯

**Dev Usage Only**
Issue Workflow

- [x] Usage
- [x] Boolean Validator
- [x] Await Message
- [ ] Commands

**Comment by UnseenFaith** [comment] 2017-03-26 18:07
1. `/\d+/.exec(args[i])[0]` We test beforehand for digits or we invalidate it. I just tested it and it works fine and as intended.
```
          if (/^<@!?\d+>$/.test(args[i]) || (client.users.has(/\d+/.exec(args[i])[0]) && args[i].length > 5)) {
```

2. The validateArgs needs to be moved outside of the if
3. I guess.
4. just no.

**Comment by kyranet** [comment] 2017-03-26 19:06
The issue with **1.** is when you insert text only, with no digits, then, nothing in the provided string maths, returning null.

**Comment by CyberiumShadow** [comment] 2017-04-04 22:21
Issue Workflow

- [x] Usage
- [ ] Boolean Validator
- [ ] Await Message
- [ ] Commands


Refer to Kyra's first comment for task list integration with issue tracker. Do not use this comment

**Comment by UnseenFaith** [comment] 2017-04-06 00:21
Issue 4 is already a part of core Komada. Closing this as everything else is finished.

**Closed as completed by UnseenFaith** 2017-04-06 00:21 UTC
Labels: SEM: Patch, Bug: Fixed
